spring:
  datasource:
    url: jdbc:mysql://localhost:3306/examdb
    password: admin
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 9292
